import type { FacilityId } from "./constants";
import type { DomainId } from "./domain";

/**
 * AIC Plan domain model.
 *
 * "AIC Plan" is the in-game name for the Settlement Tech Tree (the
 * upstream tech-tree tables in the game-data dump). Two top-level plans
 * exist today:
 *
 *   - `tech_group_tundra` → in-game "Basic AIC Plan"   (domain_1, Valley IV)
 *   - `tech_group_jinlong` → in-game "Wuling AIC Plan" (domain_2, Wuling)
 *
 * Each plan groups tech nodes into linear-prereq layers ("Basic AIC I/II/III").
 * Nodes either unlock a building blueprint, unlock a recipe-mode on a
 * building, or raise a per-domain placement cap on a facility.
 *
 * Only nodes the calculator can meaningfully model are surfaced (the
 * extraction script applies a "lean" filter).
 * Battle/decor/marker/travel/power/logistics nodes are dropped because the
 * calculator doesn't reference those facilities.
 *
 * The AIC Plan is ONE category of per-domain settings; the UI hosts it
 * inside a generic `DomainSection`. Future categories (region limits,
 * power budget, …) sit as sibling cards. See `src/types/domain.ts` for
 * the generic domain primitives.
 *
 * Lifecycle: structural data is regenerated by `pnpm run extract:aic`;
 * runtime state (the user's research set + custom cap overrides) is owned
 * by `useDomainSettings`.
 */

/**
 * Closed-enum group ids. The set is finite (2 entries) and stable across
 * dumps, so a literal-string union is the right shape — distinct from the
 * branded ids used for layers / nodes / domains which the dump may extend.
 */
const AicGroupId = {
  BASIC: "tech_group_tundra",
  WULING: "tech_group_jinlong",
} as const;
type AicGroupId = (typeof AicGroupId)[keyof typeof AicGroupId];

/**
 * Brand intersection for layer ids ("Basic AIC I/II/III" rows).
 * The extraction script produces them in a stable, sorted form; the brand
 * keeps the type system honest against accidental string mixing.
 */
type AicLayerId = string & { readonly __brand: "AicLayerId" };

/**
 * Brand intersection for individual tech-node ids
 * (e.g. `tech_jinlong_3_xiranite_oven_amount_3`).
 */
type AicTechId = string & { readonly __brand: "AicTechId" };

/**
 * Action a tech node performs when researched.
 *
 * - `unlock` — a plain tech unlock in the game data. Resolves the
 *   blueprint item the node grants back to one of our calc-modelled
 *   `FacilityId` values.
 * - `modeUnlock` — a machine-mode unlock in the game data. Activates an
 *   additional recipe-mode (e.g. "liquid") on an already-unlockable facility.
 *   In Step 2 these filter recipes whose `formulaGroupId` belongs to a
 *   locked mode.
 * - `capRaise` — a placement-cap raise in the game data. Adds `delta`
 *   to the facility's per-domain placement cap. In Step 1 these are
 *   display-only; Step 5 (future) would enforce.
 *
 * Nodes whose upstream action falls outside this set are filtered out at
 * extraction time — they never reach `AicNode` instances.
 */
type AicAction =
  | { kind: "unlock"; facilityId: FacilityId }
  | { kind: "modeUnlock"; facilityId: FacilityId; modeName: string }
  | {
      kind: "capRaise";
      facilityId: FacilityId;
      domainId: DomainId;
      delta: number;
    };

/**
 * One tech node — a checkbox in the AIC tree.
 *
 * `preNodes` has been transitively re-pointed through any nodes dropped by
 * the lean filter: every id here resolves to another `AicNode`. The user
 * sees a consistent prereq DAG containing only calc-relevant nodes.
 *
 * `alreadyUnlocked: true` means the game grants this tech by default. The
 * UI surfaces these as muted / non-interactive rows, and `useAicResearch`
 * seeds them into the default research set.
 *
 * `additionalFacilities` is non-empty when a single tech unlocks multiple
 * facilities (e.g. the Depot Bus tech grants both `loader_1` and
 * `unloader_1`). The discriminated `action` carries the primary facility;
 * the runtime treats the additional ones as unlocking together. Mode
 * unlocks and cap raises always have an empty `additionalFacilities`.
 */
type AicNode = {
  readonly id: AicTechId;
  readonly groupId: AicGroupId;
  readonly layerId: AicLayerId;
  readonly preNodes: readonly AicTechId[];
  readonly alreadyUnlocked: boolean;
  readonly action: AicAction;
  readonly additionalFacilities: readonly FacilityId[];
};

/**
 * A layer inside a plan. `order` is 1/2/3 corresponding to the in-game
 * "I/II/III" suffix; layers are rendered in ascending order top-to-bottom.
 */
type AicLayer = {
  readonly id: AicLayerId;
  readonly groupId: AicGroupId;
  readonly order: number;
};

/**
 * A plan. `domainId` is the in-game region these techs belong to —
 * Basic AIC ↔ domain_1, Wuling AIC ↔ domain_2.
 */
type AicGroup = {
  readonly id: AicGroupId;
  readonly domainId: DomainId;
};

/**
 * The base per-domain placement cap for a facility as defined by the
 * game data's per-building placement-limit array (paired with its
 * placeable-domains list). Used as the starting value for
 * cap-raise math and for the "Game cap: N" hint in the Facility-limits
 * UI.
 *
 * Facilities without a per-domain limit do not appear in this map.
 */
type FacilityBaseCap = {
  readonly facilityId: FacilityId;
  readonly domainId: DomainId;
  readonly base: number;
};

export { AicGroupId };
export type {
  AicLayerId,
  AicTechId,
  AicAction,
  AicNode,
  AicLayer,
  AicGroup,
  FacilityBaseCap,
};
