/**
 * gen-item-codes — maintains `src/data/item-codes.ts`, the stable,
 * APPEND-ONLY item→code registry that keeps shareable plan URLs short.
 *
 * STANDALONE + self-contained: it parses committed files only (the
 * `ItemId` enum in `src/types/constants.ts` + the existing registry), so
 * unlike the game-data extractors it needs no data dir and anyone can run
 * it — `pnpm run extract:item-codes`. Run it after `extract:items`.
 *
 * A code is the entry's `index.toString(36)`. Codes must NEVER change or
 * be reused (shared URLs reference them), so this only:
 *   - keeps every existing entry at its index (codes stay stable),
 *   - tombstones ("") ids that left the enum (index retired, not reused),
 *   - appends new ItemIds at the end.
 *
 * The completeness guard in `src/tests/lib/item-code.test.ts` fails if a
 * new item has no code (i.e. this wasn't re-run) — that's the "fail if we
 * forget" backstop.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const CONSTANTS_PATH = path.join(REPO_ROOT, "src", "types", "constants.ts");
const OUT_PATH = path.join(REPO_ROOT, "src", "data", "item-codes.ts");

/** Every `ItemId` value, in enum order (parsed, not imported). */
function currentItemIds(): string[] {
  const src = fs.readFileSync(CONSTANTS_PATH, "utf8");
  const block = src.match(/const ItemId = \{([\s\S]*?)\} as const;/);
  if (!block) {
    throw new Error("gen-item-codes: ItemId enum not found in constants.ts");
  }
  return [...block[1].matchAll(/:\s*"([^"]+)"/g)].map((m) => m[1]);
}

/** The previously-emitted table (or [] on first run), tombstones included. */
function existingTable(): string[] {
  if (!fs.existsSync(OUT_PATH)) return [];
  const src = fs.readFileSync(OUT_PATH, "utf8");
  const arr = src.match(/itemCodeTable[^[]*\[([\s\S]*?)\]/);
  if (!arr) return [];
  return [...arr[1].matchAll(/"([^"]*)"/g)].map((m) => m[1]);
}

function run(): void {
  const ids = currentItemIds();
  const live = new Set(ids);

  const table = existingTable();
  // Retire ids that left the enum — keep the index (never reuse a code).
  for (let i = 0; i < table.length; i++) {
    if (table[i] !== "" && !live.has(table[i])) table[i] = "";
  }
  // Append genuinely-new ids (enum order) at the end.
  const known = new Set(table);
  let appended = 0;
  for (const id of ids) {
    if (!known.has(id)) {
      table.push(id);
      known.add(id);
      appended++;
    }
  }

  const lines = [
    "/**",
    " * AUTO-GENERATED by `pnpm run extract:item-codes` — DO NOT EDIT BY HAND.",
    " *",
    " * Stable, APPEND-ONLY item→code registry for shareable URLs. A code is",
    " * the entry's `index.toString(36)`; codes must never change or be reused",
    ' * (shared plan URLs reference them). Re-running only appends new items and',
    ' * tombstones ("") removed ones — it never reorders existing entries.',
    " *",
    " * Re-run after `extract:items`; `item-code.test.ts` fails if an item",
    " * lacks a code.",
    " */",
    "export const itemCodeTable: readonly string[] = [",
    ...table.map((id) => `  ${JSON.stringify(id)},`),
    "];",
    "",
  ];
  fs.writeFileSync(OUT_PATH, lines.join("\n"));

  const liveCount = table.filter((id) => id !== "").length;
  console.log(
    `[gen-item-codes] wrote ${path.relative(REPO_ROOT, OUT_PATH)} — ` +
      `${liveCount} items, ${appended} appended, ` +
      `${table.length - liveCount} tombstones, next code "${table.length.toString(36)}"`,
  );
}

run();
