import { describe, test, expect } from "vitest";
import type { Edge } from "@xyflow/react";
import { getNeighborhood, getChain } from "@/lib/flow-spotlight";
import { getItemEdgeColor } from "@/components/flow/flow-utils";
import { itemIconColors } from "@/data/item-colors";
import { items } from "@/data";

/**
 * Synthetic graph:
 *
 *   A ──e1──▶ B ──e2──▶ C ──e3──▶ D
 *   X ──e4──────▶ B     C ──e5──▶ Y
 *
 * A and X both feed B; C fans out to D and Y.
 */
const edge = (id: string, source: string, target: string): Edge => ({
  id,
  source,
  target,
});

const EDGES: Edge[] = [
  edge("e1", "A", "B"),
  edge("e2", "B", "C"),
  edge("e3", "C", "D"),
  edge("e4", "X", "B"),
  edge("e5", "C", "Y"),
];

describe("getNeighborhood", () => {
  test("returns the node, incident edges, and far-end nodes only", () => {
    const { nodeIds, edgeIds } = getNeighborhood(EDGES, "B");
    expect([...nodeIds].sort()).toEqual(["A", "B", "C", "X"]);
    expect([...edgeIds].sort()).toEqual(["e1", "e2", "e4"]);
  });

  test("fan-out node includes consumers and supplier", () => {
    const { nodeIds, edgeIds } = getNeighborhood(EDGES, "C");
    expect([...nodeIds].sort()).toEqual(["B", "C", "D", "Y"]);
    expect([...edgeIds].sort()).toEqual(["e2", "e3", "e5"]);
  });

  test("isolated node spotlights only itself", () => {
    const { nodeIds, edgeIds } = getNeighborhood(EDGES, "Z");
    expect([...nodeIds]).toEqual(["Z"]);
    expect(edgeIds.size).toBe(0);
  });
});

describe("getChain", () => {
  test("terminal node: full upstream cone, no unrelated branches", () => {
    const { nodeIds, edgeIds } = getChain(EDGES, ["D"]);
    // Upstream of D: C, B, A, X. Y and e5 are NOT on any path to D.
    expect([...nodeIds].sort()).toEqual(["A", "B", "C", "D", "X"]);
    expect([...edgeIds].sort()).toEqual(["e1", "e2", "e3", "e4"]);
  });

  test("mid-chain node: union of upstream and downstream", () => {
    const { nodeIds, edgeIds } = getChain(EDGES, ["C"]);
    expect([...nodeIds].sort()).toEqual(["A", "B", "C", "D", "X", "Y"]);
    expect([...edgeIds].sort()).toEqual(["e1", "e2", "e3", "e4", "e5"]);
  });

  test("source node: downstream only", () => {
    const { nodeIds, edgeIds } = getChain(EDGES, ["X"]);
    // Downstream of X: B, C, D, Y. Upstream of B (A, e1) joins because
    // the chain includes B's full downstream, not B's other suppliers…
    // — it must NOT: A supplies B but is not reachable from X in either
    // direction starting at X.
    expect(nodeIds.has("A")).toBe(false);
    expect(edgeIds.has("e1")).toBe(false);
    expect([...nodeIds].sort()).toEqual(["B", "C", "D", "X", "Y"]);
    expect([...edgeIds].sort()).toEqual(["e2", "e3", "e4", "e5"]);
  });

  test("multi-seed union", () => {
    const { nodeIds, edgeIds } = getChain(EDGES, ["X", "A"]);
    expect([...nodeIds].sort()).toEqual(["A", "B", "C", "D", "X", "Y"]);
    expect([...edgeIds].sort()).toEqual(["e1", "e2", "e3", "e4", "e5"]);
  });

  test("terminates on cycles (backward edges form SCCs)", () => {
    const cyclic: Edge[] = [
      edge("c1", "P", "Q"),
      edge("c2", "Q", "P"), // backward edge: cycle
      edge("c3", "Q", "R"),
    ];
    const { nodeIds, edgeIds } = getChain(cyclic, ["P"]);
    expect([...nodeIds].sort()).toEqual(["P", "Q", "R"]);
    expect([...edgeIds].sort()).toEqual(["c1", "c2", "c3"]);
  });

  test("no seeds yields empty sets", () => {
    const { nodeIds, edgeIds } = getChain(EDGES, []);
    expect(nodeIds.size).toBe(0);
    expect(edgeIds.size).toBe(0);
  });
});

describe("getItemEdgeColor", () => {
  test("icon-mapped item: theme-var oklch with per-item chroma factor and hue", () => {
    const color = getItemEdgeColor("item_xiranite_powder");
    const entry = itemIconColors["item_xiranite_powder"];
    expect(entry).toBeDefined();
    expect(color).toBe(
      `oklch(var(--flow-edge-l) calc(var(--flow-edge-c) * ${entry.c}) ${entry.h})`,
    );
    // Deterministic across calls.
    expect(getItemEdgeColor("item_xiranite_powder")).toBe(color);
  });

  test("unmapped item: hash fallback with full theme chroma", () => {
    const color = getItemEdgeColor("item_not_a_real_item_zzz");
    expect(color).toMatch(
      /^oklch\(var\(--flow-edge-l\) var\(--flow-edge-c\) \d{1,3}\)$/,
    );
    const hue = Number(color.match(/(\d+)\)$/)?.[1]);
    expect(hue).toBeGreaterThanOrEqual(0);
    expect(hue).toBeLessThan(360);
  });

  test("missing id falls back to muted foreground", () => {
    expect(getItemEdgeColor(undefined)).toBe("var(--muted-foreground)");
  });
});

describe("itemIconColors (generated by extract:item-colors)", () => {
  test("covers every item that ships an icon", () => {
    // Every real item id should be colourable from its icon; the only
    // expected miss is the synthetic __multi_target__ pseudo-item.
    const missing = items
      .map((i) => i.id as string)
      .filter((id) => !id.startsWith("__") && !itemIconColors[id]);
    expect(missing).toEqual([]);
  });

  test("hue and chroma factor stay in range", () => {
    const entries = Object.values(itemIconColors);
    expect(entries.length).toBeGreaterThan(100);
    for (const { h, c } of entries) {
      expect(Number.isInteger(h)).toBe(true);
      expect(h).toBeGreaterThanOrEqual(0);
      expect(h).toBeLessThan(360);
      expect(c).toBeGreaterThanOrEqual(0.25);
      expect(c).toBeLessThanOrEqual(1.25);
    }
  });

  test("no two entries look the same (hue within 2° AND chroma within 0.08)", () => {
    const entries = Object.entries(itemIconColors);
    const collisions: string[] = [];
    for (let i = 0; i < entries.length; i++) {
      for (let j = i + 1; j < entries.length; j++) {
        const [idA, a] = entries[i];
        const [idB, b] = entries[j];
        const dh = Math.abs(a.h - b.h);
        const hueDist = Math.min(dh, 360 - dh);
        if (hueDist < 2 && Math.abs(a.c - b.c) < 0.08) {
          collisions.push(`${idA} vs ${idB}`);
        }
      }
    }
    expect(collisions).toEqual([]);
  });

  test("semantic anchors: copper is warm, sewage is muted", () => {
    // Coarse sanity that extraction reads icons, not noise. Copper ore's
    // icon is orange (warm hue, high chroma); sewage's is murky (low
    // chroma factor).
    const copper = itemIconColors["item_copper_ore"];
    expect(copper.h).toBeGreaterThanOrEqual(15);
    expect(copper.h).toBeLessThanOrEqual(90);
    expect(copper.c).toBeGreaterThan(0.5);
    const sewage = itemIconColors["item_liquid_sewage"];
    expect(sewage.c).toBeLessThanOrEqual(0.4);
  });
});
