/**
 * Tests for `defaultRawCapsByDomain` (AUTO-GENERATED by
 * `pnpm run extract:raw-caps` into `src/data/raw-caps.ts`).
 *
 * Three layers of coverage:
 *
 *   1. **Data shape** — exact per-region snapshot of the max mining
 *      output (items/min) at max Regional Development Level, from the
 *      dump's scene data (mining spots × purity-density schedules ×
 *      20/min) plus a few panel-verified manual overrides for the 1.4
 *      Wuling gas/expansion caps the scene data can't produce (see
 *      `MANUAL_CAP_OVERRIDES` in `scripts/extract-raw-caps.ts`). Catches
 *      accidental edits / regeneration drift.
 *
 *   2. **Invariants** vs the rest of the data layer:
 *      a. every capped item is available in that region
 *         (`rawAvailabilityByDomain`) — a cap on an unsourceable raw
 *         would be dead data;
 *      b. every capped item is a bound raw (`rawMaterialSources`) and
 *         non-liquid (liquids are costless / pump-governed, never
 *         default-capped);
 *      c. every domain key is in the domain registry, mirroring the
 *         coverage invariant on `rawAvailabilityByDomain`.
 *
 *   3. **Exclusions** — Burdo-Muck (a gather item, not rig-mined) and
 *      the liquid raws must have NO default cap anywhere: absence is
 *      what keeps them unlimited-by-default in the caps aggregation
 *      (`buildRawMaterialCaps`).
 */

import { describe, expect, test } from "vitest";
import {
  defaultRawCapsByDomain,
  items,
  rawAvailabilityByDomain,
  rawMaterialSources,
} from "@/data";
import { domains } from "@/data/aic-plans";
import { DomainId } from "@/types/domain";
import { ItemId } from "@/types/constants";

describe("defaultRawCapsByDomain — data shape", () => {
  test("Valley IV (domain_1) max mining output", () => {
    expect(defaultRawCapsByDomain.get(DomainId.DOMAIN_1)).toEqual(
      new Map<ItemId, number>([
        [ItemId.ITEM_IRON_ORE, 1080],
        [ItemId.ITEM_ORIGINIUM_ORE, 560],
        [ItemId.ITEM_QUARTZ_SAND, 240],
      ]),
    );
  });

  test("Wuling (domain_2) max mining output", () => {
    expect(defaultRawCapsByDomain.get(DomainId.DOMAIN_2)).toEqual(
      new Map<ItemId, number>([
        // Panel-verified MANUAL OVERRIDES (see MANUAL_CAP_OVERRIDES in
        // scripts/extract-raw-caps.ts). The 1.4 "Homecoming" Wuling
        // expansion added mineable gas vents across the map + two new
        // regions (Yinglung Pass, North Wuling Exclusion Zone) with more
        // gas + copper — none of it in the extractable scene data (its
        // lone gas scene map02_lv008 is a gas-environment cluster, not
        // the mineable vents; no table stores regional caps). Read off
        // the in-game region panel at dev 24:
        //   Cuprium 420 = 18 high (360) + new region (1 high + 4 low = 60)
        //   Inergen 460 = 23 High-Purity vents
        //   Xiragen 100 = 5 High-Purity vents (North Wuling)
        [ItemId.ITEM_COPPER_ORE, 420],
        [ItemId.ITEM_GAS_INERT, 460],
        [ItemId.ITEM_GAS_XIRANITE, 100],
        // Extractor-computed (scene data still correct for these):
        [ItemId.ITEM_IRON_ORE, 120],
        [ItemId.ITEM_ORIGINIUM_ORE, 540],
      ]),
    );
  });

  test("every cap is a positive finite items/min rate", () => {
    for (const [domainId, caps] of defaultRawCapsByDomain) {
      for (const [itemId, rate] of caps) {
        expect(
          Number.isFinite(rate) && rate > 0,
          `${domainId}/${itemId} rate ${rate}`,
        ).toBe(true);
      }
    }
  });
});

describe("defaultRawCapsByDomain — invariants vs the data layer", () => {
  test("every capped item is available in that region", () => {
    // A default cap for a raw the region can't source would never
    // surface in the Raw Limits UI (rows come from
    // `rawAvailabilityByDomain`) yet would still constrain the LP —
    // dead, misleading data.
    for (const [domainId, caps] of defaultRawCapsByDomain) {
      const available = rawAvailabilityByDomain.get(domainId);
      expect(available, `region ${domainId}`).toBeDefined();
      for (const itemId of caps.keys()) {
        expect(
          available!.has(itemId),
          `${itemId} capped but not available in ${domainId}`,
        ).toBe(true);
      }
    }
  });

  test("every capped item is a non-liquid bound raw", () => {
    const itemsById = new Map(items.map((i) => [i.id, i] as const));
    for (const [domainId, caps] of defaultRawCapsByDomain) {
      for (const itemId of caps.keys()) {
        expect(
          rawMaterialSources.has(itemId),
          `${itemId} (${domainId}) has no rawMaterialSources entry`,
        ).toBe(true);
        expect(
          itemsById.get(itemId)?.isLiquid === true,
          `${itemId} (${domainId}) is a liquid — liquids are never default-capped`,
        ).toBe(false);
      }
    }
  });

  test("every domain key is in the domain registry", () => {
    const registered = new Set(domains.map((d) => d.id));
    for (const domainId of defaultRawCapsByDomain.keys()) {
      expect(registered.has(domainId), `domain ${domainId}`).toBe(true);
    }
  });
});

describe("defaultRawCapsByDomain — exclusions stay unlimited", () => {
  test("Burdo-Muck has no default cap in any region", () => {
    // Burdo-Muck is gathered from Burdos in the world, not rig-mined at
    // mineral beds — there is no "max mining output" to default to.
    // Absence of the entry = unlimited (see `buildRawMaterialCaps`).
    for (const [domainId, caps] of defaultRawCapsByDomain) {
      expect(
        caps.has(ItemId.ITEM_MUCK_FECES_1),
        `Burdo-Muck capped in ${domainId}`,
      ).toBe(false);
    }
  });

  test("liquid raws have no default cap in any region", () => {
    for (const [domainId, caps] of defaultRawCapsByDomain) {
      for (const liquid of [
        ItemId.ITEM_LIQUID_WATER,
        ItemId.ITEM_LIQUID_ACID,
      ]) {
        expect(caps.has(liquid), `${liquid} capped in ${domainId}`).toBe(
          false,
        );
      }
    }
  });
});
