/**
 * AUTO-GENERATED by `pnpm run extract:url-codes` — DO NOT EDIT BY HAND.
 *
 * Stable, APPEND-ONLY FacilityId→code registry for shareable
 * URLs (AIC facility-cap overrides).
 *
 * A code is the entry's `index.toString(36)`; codes must never change or
 * be reused (shared plan URLs reference them). Re-running only appends
 * new entries and tombstones ("") removed ones — it never reorders
 * existing entries.
 *
 * Re-run after `extract:all`; `url-codes.test.ts` fails if an id lacks a
 * code.
 */
export const facilityCodeTable: readonly string[] = [
  "component_mc_1",
  "dismantler_1",
  "filling_powder_mc_1",
  "furnance_1",
  "gas_pump_1",
  "gas_reactor_1",
  "grinder_1",
  "liquid_clean_gate_1",
  "liquid_cleaner_1",
  "liquid_purifier_1",
  "loader_1",
  "mix_pool_1",
  "mix_pool_2",
  "planter_1",
  "power_station_1",
  "pump_1",
  "pump_2",
  "seedcollector_1",
  "shaper_1",
  "thickener_1",
  "assebling",
  "tools_assebling_mc_1",
  "transmuter_1",
  "transmuter_2",
  "unloader_1",
  "vaporizer_1",
  "winder_1",
  "xiranite_oven_1",
];
