/**
 * AUTO-GENERATED by `pnpm run extract:url-codes` — DO NOT EDIT BY HAND.
 *
 * Stable, APPEND-ONLY RegionStructureId→code registry for shareable
 * URLs (disabled map structures).
 *
 * A code is the entry's `index.toString(36)`; codes must never change or
 * be reused (shared plan URLs reference them). Re-running only appends
 * new entries and tombstones ("") removed ones — it never reorders
 * existing entries.
 *
 * Re-run after `extract:all`; `url-codes.test.ts` fails if an id lacks a
 * code.
 */
export const structureCodeTable: readonly string[] = [
  "liquid_clean_gate_1",
  "liquid_clean_gate_2",
  "liquid_clean_gate_3",
  "liquid_recycle_gate_1",
];
