/**
 * AUTO-GENERATED by `pnpm run extract:url-codes` — DO NOT EDIT BY HAND.
 *
 * Stable, APPEND-ONLY AicTechId→code registry for shareable
 * URLs (the unresearched-tech list, the largest field in the blob).
 *
 * A code is the entry's `index.toString(36)`; codes must never change or
 * be reused (shared plan URLs reference them). Re-running only appends
 * new entries and tombstones ("") removed ones — it never reorders
 * existing entries.
 *
 * Re-run after `extract:all`; `url-codes.test.ts` fails if an id lacks a
 * code.
 */
export const techCodeTable: readonly string[] = [
  "tech_jinlong_3_liquid_purifier_1",
  "tech_jinlong_3_mix_2",
  "tech_jinlong_3_pump_2",
  "tech_jinlong_3_xiranite_enr_formula",
  "tech_jinlong_3_xiranite_oven_amount_3",
  "tech_jinlong_4_gas_reactor_1",
  "tech_jinlong_4_liquid_purifier_mode_1",
  "tech_jinlong_4_vaporizer_1",
  "tech_jinlong_2_furnance_mode_1",
  "tech_jinlong_2_liquid_cleaner_1",
  "tech_jinlong_2_xiranite_oven_amount_2",
  "tech_jinlong_4_filling_and_dismantler_mode_2",
  "tech_jinlong_4_gas_pump_1",
  "tech_jinlong_4_shaper_mode_2",
  "tech_jinlong_4_transmuter_1",
  "tech_jinlong_4_transmuter_2",
  "tech_jinlong_1_dismantler_1",
  "tech_jinlong_1_filling_mode_1",
  "tech_jinlong_1_mix_1",
  "tech_jinlong_1_planter_mode_1",
  "tech_jinlong_1_pump_1",
  "tech_jinlong_1_xiranite_oven_1",
  "tech_jinlong_1_xiranite_oven_amount_1",
  "tech_tundra_3_thickener_1",
  "tech_tundra_1_cmpt_1",
  "tech_tundra_1_furnance_1",
  "tech_tundra_1_grinder_1",
  "tech_tundra_1_shaper_1",
  "tech_tundra_1_winder_1",
  "tech_tundra_2_asm_1",
  "tech_tundra_2_field_1",
  "tech_tundra_2_filling_1",
  "tech_tundra_2_plant_1",
];
